Repository square/bazel_maven_repository, pull requests merged in 2019-09, with the labels that each got.

#83 Relax name mangling of artifact_ids
  maven/artifacts.bzl
  maven/globals.bzl
  maven/maven.bzl
  maven/tests/all_tests.bzl
  maven/tests/strings_test.bzl
  maven/utils.bzl
  test/test_workspace/WORKSPACE
  test/test_workspace/build_substitution_templates.bzl
  test/test_workspace/java/blah/BUILD.bazel
Labels: Priority-2, Type-enhancement

#84 Convert to using read() (a 0.29+ api).
  .travis.yml
  README.md
  maven/artifacts.bzl
  maven/fetch.bzl
  maven/globals.bzl
  maven/maven.bzl
  maven/poms.bzl
  maven/tests/fetch_test.bzl
  maven/tests/maven_test.bzl
  maven/tests/poms_merging_test.bzl
  maven/tests/poms_test.bzl
  maven/utils.bzl
Labels: Priority-1, Type-cleanup

#88 Add support for AndroidX
  maven/jetifier.bzl
  maven/maven.bzl
  maven/poms.bzl
Labels: Priority-0, Type-enhancement
